version: '3'
services: 
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
     - "3307:3306"
    expose:
      - 3307 
  node-app:
   build: .
   links:
      - mysql
   depends_on:
      - mysql
   ports: 
    - 5000:3000
 