version: "3"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    expose:
      - "3306"
      - "33060"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  node-app:
    container_name: TRAVIA_VISIT_NEPAL
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 5000:3000
    volumes:
      - ./:/usr/app
volumes:
  mysql:
